# Generated by Django 4.0.4 on 2022-05-11 13:01

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sample", models.UUIDField()),
                ("laborant", models.UUIDField()),
                ("lab", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Finished", "Finished"),
                            ("Pending", "Pending"),
                            ("In progress", "In Progress"),
                        ],
                        max_length=12,
                    ),
                ),
                ("structure", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "tools",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), size=None
                    ),
                ),
            ],
        ),
    ]
